@HOST = http://localhost:5294
@accountId = ""

###
GET {{HOST}}/api/account

###
GET {{HOST}}/api/account/{{accountId}}

###
POST {{HOST}}/api/account
Content-Type: application/json

{
    "Username": "tobinek",
    "Email": "tobiasfilgas@gmail.com",
    "Password": "password123"
}
